linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - misspell
  enable-all: false

issues:
  exclude-use-default: false

run:
  concurrency: 2
