
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.2.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.38.28"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.16.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.8.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "v1.1.3"

[[constraint]]
  name = "github.com/buger/jsonparser"
  revision = "2cac668e8456b4284edb0715e17e2af02d3ec993"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"
